name: desk_monkey
description: A responsive desk assistant.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^0.6.9
  cupertino_icons: ^1.0.2
  injectable: ^1.0.7
  get_it: ^5.0.4
  stacked: ^1.7.7
  stacked_themes: ^0.2.2+2
  wakelock: ^0.4.0

  # Requires Android and iOS Setup
  porcupine: ^1.9.1
  speech_to_text: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.9
  build_runner: ^1.10.2
  injectable_generator: ^1.1.2
  pedantic: ^1.9.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

